name: Cloudcore IAC Destroy

on:
  workflow_dispatch:   # This allows manual triggering via GitHub Actions UI
    inputs:
      confirm:
        description: 'Confirm Destroy (type "yes" to proceed)'
        required: true
        default: 'no'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-1

jobs:
  terraform-destroy:
    name: "Destroy Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform  # Adjust if your terraform directory is different

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan (Destroy)
        id: plan
        run: terraform plan -destroy -no-color -input=false -out destroy_planfile
        continue-on-error: true

      - name: Terraform Destroy (Apply Destroy Plan)
        id: destroy
        if: ${{ github.event.inputs.confirm == 'yes' }}   # Only destroy if confirmation is "yes"
        run: terraform apply -auto-approve -input=false -parallelism=1 destroy_planfile

